
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author puddaa
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dotButton = new javax.swing.JButton();
        numZeroButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        numSevenButton = new javax.swing.JButton();
        numEightButton = new javax.swing.JButton();
        numNineButton = new javax.swing.JButton();
        numFourButton = new javax.swing.JButton();
        numFiveButton = new javax.swing.JButton();
        numSixButton = new javax.swing.JButton();
        numOneButton = new javax.swing.JButton();
        numTwoButton = new javax.swing.JButton();
        numThreeButton = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        clearEntryButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        dotButton.setText(".");
        dotButton.setAlignmentY(0.0F);
        dotButton.setFocusPainted(false);
        dotButton.setFocusable(false);
        dotButton.setMaximumSize(new java.awt.Dimension(39, 23));
        dotButton.setMinimumSize(new java.awt.Dimension(39, 23));
        dotButton.setPreferredSize(new java.awt.Dimension(39, 23));
        dotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotButtonMouseClicked(evt);
            }
        });

        numZeroButton.setText("0");
        numZeroButton.setAlignmentY(0.0F);
        numZeroButton.setFocusPainted(false);
        numZeroButton.setFocusable(false);
        numZeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numZeroButtonMouseClicked(evt);
            }
        });

        equalButton.setText("=");
        equalButton.setAlignmentY(0.0F);
        equalButton.setFocusPainted(false);
        equalButton.setFocusable(false);
        equalButton.setMargin(new java.awt.Insets(2, 12, 2, 12));
        equalButton.setMaximumSize(new java.awt.Dimension(39, 23));
        equalButton.setMinimumSize(new java.awt.Dimension(39, 23));
        equalButton.setPreferredSize(new java.awt.Dimension(39, 23));

        plusButton.setText("+");
        plusButton.setAlignmentY(0.0F);
        plusButton.setFocusPainted(false);
        plusButton.setFocusable(false);
        plusButton.setMargin(new java.awt.Insets(2, 12, 2, 12));

        minusButton.setText("-");
        minusButton.setAlignmentY(0.0F);
        minusButton.setFocusPainted(false);
        minusButton.setFocusable(false);
        minusButton.setMaximumSize(new java.awt.Dimension(39, 23));
        minusButton.setMinimumSize(new java.awt.Dimension(39, 23));
        minusButton.setPreferredSize(new java.awt.Dimension(39, 23));

        multiplyButton.setText("*");
        multiplyButton.setAlignmentY(0.0F);
        multiplyButton.setFocusPainted(false);
        multiplyButton.setFocusable(false);

        numSevenButton.setText("7");
        numSevenButton.setAlignmentY(0.0F);
        numSevenButton.setFocusPainted(false);
        numSevenButton.setFocusable(false);
        numSevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numSevenButtonMouseClicked(evt);
            }
        });

        numEightButton.setText("8");
        numEightButton.setAlignmentY(0.0F);
        numEightButton.setFocusPainted(false);
        numEightButton.setFocusable(false);
        numEightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numEightButtonMouseClicked(evt);
            }
        });

        numNineButton.setText("9");
        numNineButton.setAlignmentY(0.0F);
        numNineButton.setFocusPainted(false);
        numNineButton.setFocusable(false);
        numNineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numNineButtonMouseClicked(evt);
            }
        });

        numFourButton.setText("4");
        numFourButton.setAlignmentY(0.0F);
        numFourButton.setFocusPainted(false);
        numFourButton.setFocusable(false);
        numFourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numFourButtonMouseClicked(evt);
            }
        });

        numFiveButton.setText("5");
        numFiveButton.setAlignmentY(0.0F);
        numFiveButton.setFocusPainted(false);
        numFiveButton.setFocusable(false);
        numFiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numFiveButtonMouseClicked(evt);
            }
        });

        numSixButton.setText("6");
        numSixButton.setAlignmentY(0.0F);
        numSixButton.setFocusPainted(false);
        numSixButton.setFocusable(false);
        numSixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numSixButtonMouseClicked(evt);
            }
        });

        numOneButton.setText("1");
        numOneButton.setAlignmentY(0.0F);
        numOneButton.setFocusPainted(false);
        numOneButton.setFocusable(false);
        numOneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numOneButtonMouseClicked(evt);
            }
        });

        numTwoButton.setText("2");
        numTwoButton.setAlignmentY(0.0F);
        numTwoButton.setFocusPainted(false);
        numTwoButton.setFocusable(false);
        numTwoButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numTwoButtonKeyPressed(evt);
            }
        });

        numThreeButton.setText("3");
        numThreeButton.setAlignmentY(0.0F);
        numThreeButton.setFocusPainted(false);
        numThreeButton.setFocusable(false);
        numThreeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numThreeButtonMouseClicked(evt);
            }
        });

        backspaceButton.setText("<-");
        backspaceButton.setFocusPainted(false);
        backspaceButton.setFocusable(false);
        backspaceButton.setMargin(new java.awt.Insets(2, 10, 2, 10));
        backspaceButton.setMaximumSize(new java.awt.Dimension(39, 23));
        backspaceButton.setMinimumSize(new java.awt.Dimension(39, 23));
        backspaceButton.setPreferredSize(new java.awt.Dimension(39, 23));
        backspaceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backspaceButtonMouseClicked(evt);
            }
        });

        clearEntryButton.setText("CE");
        clearEntryButton.setFocusPainted(false);
        clearEntryButton.setFocusable(false);
        clearEntryButton.setMargin(new java.awt.Insets(2, 10, 2, 10));
        clearEntryButton.setMaximumSize(new java.awt.Dimension(39, 23));
        clearEntryButton.setMinimumSize(new java.awt.Dimension(39, 23));
        clearEntryButton.setPreferredSize(new java.awt.Dimension(39, 23));
        clearEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntryButtonActionPerformed(evt);
            }
        });

        clearButton.setText("C");
        clearButton.setFocusPainted(false);
        clearButton.setFocusable(false);

        divideButton.setText("/");
        divideButton.setFocusPainted(false);
        divideButton.setFocusable(false);
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(backspaceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numSevenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numFourButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numOneButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numZeroButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numEightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numFiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numTwoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numThreeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numSixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numNineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiplyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {numEightButton, numFiveButton, numFourButton, numNineButton, numOneButton, numSevenButton, numSixButton, numTwoButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton)
                    .addComponent(divideButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numSevenButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numEightButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numNineButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(multiplyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numFourButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numFiveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numSixButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOneButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numTwoButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numThreeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numZeroButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dotButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(33, 36));
        jPanel2.setMinimumSize(new java.awt.Dimension(33, 36));

        display.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display.setText("0");
        display.setMaximumSize(new java.awt.Dimension(210, 36));
        display.setMinimumSize(new java.awt.Dimension(210, 36));
        display.setPreferredSize(new java.awt.Dimension(210, 36));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearEntryButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divideButtonActionPerformed

    private void numOneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numOneButtonMouseClicked
        numericAction("1");
    }//GEN-LAST:event_numOneButtonMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch(evt.getKeyChar()){
            case KeyEvent.VK_1:
                numericAction("1");
                break;
            case KeyEvent.VK_2:
                numericAction("2");
                break;
            case KeyEvent.VK_3:
                numericAction("3");
                break;
            case KeyEvent.VK_4:
                numericAction("4");
                break;
            case KeyEvent.VK_5:
                numericAction("5");
                break;
            case KeyEvent.VK_6:
                numericAction("6");
                break;
            case KeyEvent.VK_7:
                numericAction("7");
                break;
            case KeyEvent.VK_8:
                numericAction("8");
                break;
            case KeyEvent.VK_9:
                numericAction("9");
                break;
            case KeyEvent.VK_0:
                numericAction("0");
                break;
            case KeyEvent.VK_BACK_SPACE:
                clearLastChar();
                break;
            case KeyEvent.VK_PERIOD:
                numericAction(".");
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void numTwoButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTwoButtonKeyPressed
        numericAction("2");
    }//GEN-LAST:event_numTwoButtonKeyPressed

    private void numThreeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numThreeButtonMouseClicked
        numericAction("3");
    }//GEN-LAST:event_numThreeButtonMouseClicked

    private void numFourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numFourButtonMouseClicked
        numericAction("4");
    }//GEN-LAST:event_numFourButtonMouseClicked

    private void numFiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numFiveButtonMouseClicked
        numericAction("5");
    }//GEN-LAST:event_numFiveButtonMouseClicked

    private void numSixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numSixButtonMouseClicked
        numericAction("6");
    }//GEN-LAST:event_numSixButtonMouseClicked

    private void numSevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numSevenButtonMouseClicked
        numericAction("7");
    }//GEN-LAST:event_numSevenButtonMouseClicked

    private void numEightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numEightButtonMouseClicked
        numericAction("8");
    }//GEN-LAST:event_numEightButtonMouseClicked

    private void numNineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numNineButtonMouseClicked
        numericAction("9");
    }//GEN-LAST:event_numNineButtonMouseClicked

    private void numZeroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numZeroButtonMouseClicked
        numericAction("0");
    }//GEN-LAST:event_numZeroButtonMouseClicked

    private void backspaceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspaceButtonMouseClicked
        clearLastChar();
    }//GEN-LAST:event_backspaceButtonMouseClicked

    private void dotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotButtonMouseClicked
        numericAction(".");
    }//GEN-LAST:event_dotButtonMouseClicked
    
    private void clearLastChar (){
        String displayText = display.getText();
        displayText = displayText.substring(0, displayText.length() - 1);
        if(displayText.length() <= 0){
            displayText = "0";
        }
        display.setText(displayText);
    }
    private void numericAction(String text){
        String displayText = display.getText();
        if(displayText.equals("0") && !text.equals(".")){
            displayText = text;
        } else {
            displayText += text;
        }
        display.setText(displayText);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearEntryButton;
    private javax.swing.JLabel display;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton numEightButton;
    private javax.swing.JButton numFiveButton;
    private javax.swing.JButton numFourButton;
    private javax.swing.JButton numNineButton;
    private javax.swing.JButton numOneButton;
    private javax.swing.JButton numSevenButton;
    private javax.swing.JButton numSixButton;
    private javax.swing.JButton numThreeButton;
    private javax.swing.JButton numTwoButton;
    private javax.swing.JButton numZeroButton;
    private javax.swing.JButton plusButton;
    // End of variables declaration//GEN-END:variables
}
